# Generated by Django 2.0 on 2020-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peopleinfogonghang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('id_no', models.CharField(max_length=100, verbose_name='身份证号')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('id_no', models.CharField(max_length=100, verbose_name='身份证号')),
                ('all_list_san', models.CharField(max_length=100, null=True, verbose_name='累计次数')),
                ('list_len_all', models.CharField(max_length=100, null=True, verbose_name='连续次数')),
                ('cumulativeCompenAmount', models.CharField(max_length=100, null=True, verbose_name='保证人代偿')),
                ('condit', models.CharField(max_length=100, null=True, verbose_name='状态')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
